In [19]:
import pandas as pd
import matplotlib as mp
import numpy as np

In [2]:
data = pd.read_csv("Sampled Data.csv")

In [4]:
data.columns = data.columns.str.replace(' ', '_')

In [5]:
data.head()

,Year,Year_Text,Month,Month_Text,Day,Day_Text,Hour,Hour_Text,Minute,Minute_Text,...,Temperature,Dew_Point,DHI,DNI,GHI,Relative_Humidity,Surface_Albedo,Pressure,Wind_Direction,Wind_Speed
0,2020,2020,1,1,1,1,0,0,0,0,...,7.0,-4.9,0,0,0,42.61,0.17,993,316,1.3
1,2020,2020,1,1,1,1,1,1,0,0,...,6.5,-4.8,0,0,0,44.18,0.17,993,322,1.3
2,2020,2020,1,1,1,1,2,2,0,0,...,6.0,-4.8,0,0,0,45.80,0.17,993,329,1.3
3,2020,2020,1,1,1,1,3,3,0,0,...,5.2,-4.8,0,0,0,48.51,0.17,993,335,1.3
4,2020,2020,1,1,1,1,4,4,0,0,...,4.9,-4.7,0,0,0,49.70,0.17,993,340,1.3

In [63]:
for i in range(1, 13):
    monthCSDHI = np.array(data[data.Month == i].Clearsky_DHI)

In [58]:
monthCSDHI.mean()

56.751344086021504

In [55]:
month = np.array(data[data.Month == 1].Clearsky_DHI)
month.mean()

67.93682795698925

In [59]:
data.Clearsky_DHI.mean()

94.33208105646631

In [14]:
month1 = data[data.Month == 1]
month1

,Year,Year_Text,Month,Month_Text,Day,Day_Text,Hour,Hour_Text,Minute,Minute_Text,...,Temperature,Dew_Point,DHI,DNI,GHI,Relative_Humidity,Surface_Albedo,Pressure,Wind_Direction,Wind_Speed
0,2020,2020,1,1,1,1,0,0,0,0,...,7.0,-4.9,0,0,0,42.61,0.17,993,316,1.3
1,2020,2020,1,1,1,1,1,1,0,0,...,6.5,-4.8,0,0,0,44.18,0.17,993,322,1.3
2,2020,2020,1,1,1,1,2,2,0,0,...,6.0,-4.8,0,0,0,45.80,0.17,993,329,1.3
3,2020,2020,1,1,1,1,3,3,0,0,...,5.2,-4.8,0,0,0,48.51,0.17,993,335,1.3
4,2020,2020,1,1,1,1,4,4,0,0,...,4.9,-4.7,0,0,0,49.70,0.17,993,340,1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2020,2020,1,1,31,31,19,19,0,0,...,11.4,2.5,0,0,0,54.23,0.19,992,350,1.1
740,2020,2020,1,1,31,31,20,20,0,0,...,10.9,2.2,0,0,0,54.99,0.19,992,353,1.1
741,2020,2020,1,1,31,31,21,21,0,0,...,10.5,2.1,0,0,0,56.16,0.19,992,352,1.1
742,2020,2020,1,1,31,31,22,22,0,0,...,10.0,2.1,0,0,0,57.96,0.19,992,352,1.1
743,2020,2020,1,1,31,31,23,23,0,0,...,9.5,2.1,0,0,0,59.85,0.19,992,352,1.1

In [15]:
month2 = data[data.Month == 2]
month2

,Year,Year_Text,Month,Month_Text,Day,Day_Text,Hour,Hour_Text,Minute,Minute_Text,...,Temperature,Dew_Point,DHI,DNI,GHI,Relative_Humidity,Surface_Albedo,Pressure,Wind_Direction,Wind_Speed
744,2020,2020,2,2,1,1,0,0,0,0,...,9.1,2.1,0,0,0,61.47,0.19,992,350,1.1
745,2020,2020,2,2,1,1,1,1,0,0,...,8.7,2.1,0,0,0,63.20,0.19,992,343,1.0
746,2020,2020,2,2,1,1,2,2,0,0,...,8.2,2.1,0,0,0,65.37,0.19,991,335,0.9
747,2020,2020,2,2,1,1,3,3,0,0,...,7.7,2.1,0,0,0,67.63,0.19,991,326,0.8
748,2020,2020,2,2,1,1,4,4,0,0,...,7.4,2.1,0,0,0,69.05,0.19,992,310,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2020,2020,2,2,29,29,19,19,0,0,...,19.4,14.7,0,0,0,74.33,0.20,988,86,2.9
1436,2020,2020,2,2,29,29,20,20,0,0,...,18.8,14.7,0,0,0,77.25,0.20,989,85,3.2
1437,2020,2020,2,2,29,29,21,21,0,0,...,18.2,15.0,0,0,0,81.42,0.20,989,82,3.4
1438,2020,2020,2,2,29,29,22,22,0,0,...,17.5,15.2,0,0,0,86.65,0.20,990,78,3.4
1439,2020,2020,2,2,29,29,23,23,0,0,...,16.8,15.5,0,0,0,92.13,0.20,990,73,3.2

In [16]:
month1.Clearsky_DHI.mean()

67.93682795698925

In [26]:
month3 = data[data.Month == 3]
month3
type(month3)

pandas.core.frame.DataFrame

In [18]:
month4 = data[data.Month == 4]
month4

,Year,Year_Text,Month,Month_Text,Day,Day_Text,Hour,Hour_Text,Minute,Minute_Text,...,Temperature,Dew_Point,DHI,DNI,GHI,Relative_Humidity,Surface_Albedo,Pressure,Wind_Direction,Wind_Speed
2184,2020,2020,4,4,1,1,0,0,0,0,...,18.5,15.1,0,0,0,80.84,0.22,987,29,1.0
2185,2020,2020,4,4,1,1,1,1,0,0,...,18.1,15.3,0,0,0,83.63,0.22,986,33,0.8
2186,2020,2020,4,4,1,1,2,2,0,0,...,18.0,15.2,0,0,0,83.64,0.22,986,37,0.9
2187,2020,2020,4,4,1,1,3,3,0,0,...,18.2,15.0,0,0,0,81.46,0.22,986,38,0.9
2188,2020,2020,4,4,1,1,4,4,0,0,...,18.3,14.7,0,0,0,79.62,0.22,986,36,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2899,2020,2020,4,4,30,30,19,19,0,0,...,31.5,17.5,0,0,0,43.18,0.20,983,3,1.1
2900,2020,2020,4,4,30,30,20,20,0,0,...,30.5,17.1,0,0,0,44.67,0.20,983,20,1.2
2901,2020,2020,4,4,30,30,21,21,0,0,...,29.7,16.9,0,0,0,46.11,0.20,984,38,1.3
2902,2020,2020,4,4,30,30,22,22,0,0,...,28.9,16.8,0,0,0,48.14,0.20,984,58,1.3
2903,2020,2020,4,4,30,30,23,23,0,0,...,28.1,16.9,0,0,0,50.73,0.20,984,80,1.2

In [31]:
for i in range(1, 12):
    print(i)

1
2
3
4
5
6
7
8
9
10
11

In [40]:
month = np.array()

TypeError: array() missing required argument 'object' (pos 1)

In [37]:
month

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])